### ISSUE TITLE
Dataset is not available

### ISSUE THREAD

**Issue by huaiyukhaw** [naveenggmu/ImageClef-2020-DrawnUI#1]
Seem like the dataset is no longer available on AICrowd. Can you please share your copy of dataset over here or at huaiyukhaw@gmail.com? Thanks

**Comment by naveenggmu** [comment]
@huaiyukhaw We had to sign an End User Agreement (EUA) for us to download the dataset and participate in the challenge. So I don't know if we (participants) are supposed to share it or not :(. Sorry man.

**Comment by huaiyukhaw** [comment]
Ahh too bad :C
